# Generated by Django 5.0.6 on 2024-07-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fields_of_study',
            new_name='course',
        ),
    ]
